spring:
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:database}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081